version: '3.4'

services:
   database:
     image: mysql:5.7
     network_mode: "host"
     env_file:
        - ./env/mysql.env
   server:
      image: eubrunomiguel/tibia
      command: sh -c "./scripts/awake.sh"
      env_file:
          - ./env/mysql.env
          - ./env/vm.env
      depends_on:
        - database
      network_mode: "host"
      ports:
        - 7171:7171
        - 7172:7172
